# Header
menu:
  Home: /
  Blog: /#blog
  About: /about
  Records: /records
  Shadowsocks: /#SS

# Site favicon
favicon: /favicon.png

# Site logo
# logo: /avatar.png

# Enable Mathjax
mathjax: true

# Enable awesome-toc
awesome_toc: true

# Enable githubRepoWidget
github_repo_widget: false